workflows:
  build-apk:
    name: Build Cordova APK
    instance_type: mac_mini_m1  # 或 linux_x64，根据需要选择
    environment:
      node: 18
      java: 17
    scripts:
      - name: Checkout code
        script: |
          echo "Code checked out"
      - name: Install Android SDK
        script: |
          echo "Android SDK already available on Codemagic"
      - name: Prepare Cordova project
        script: |
          cd android_apk/cordova_example
          npm ci
          npx cordova platform remove android || true
          npx cordova platform add android
      - name: Build unsigned APK
        script: |
          cd android_apk/cordova_example
          npx cordova build android --release --no-update-notifier
      - name: Sign APK
        script: |
          cd android_apk/cordova_example
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
            APK_UNSIGNED=$(find platforms/android/app/build/outputs/apk/release -name '*.apk' ! -name '*signed*' | head -1)
            if [ -n "$APK_UNSIGNED" ]; then
              apksigner sign --ks release.keystore --ks-key-alias "$KEY_ALIAS" --ks-pass "pass:$KEYSTORE_PASSWORD" --key-pass "pass:$KEY_PASSWORD" --out app-release-signed.apk "$APK_UNSIGNED"
              echo "APK signed successfully"
            else
              echo "No unsigned APK found"
            fi
          else
            echo "No keystore provided, skipping signing"
          fi
    artifacts:
      - android_apk/cordova_example/platforms/android/app/build/outputs/apk/release/*.apk
    publishing:
      google_play:
        # 如果需要发布到 Google Play，配置这里
        # credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        # track: internal
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true