# Generated by Django 4.2.27 on 2026-01-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_familymember_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='audio_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
